apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  labels:
    app: mywebapp
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      nodeSelector:
        env: development
      containers:
      - name: mywebapp-ctr
        image: chaitannyaa/calculator:latest
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
