apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30430

