apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  labels:
    app1: mywebapp1
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app1: mywebapp1
  template:
    metadata:
      labels:
        app1: mywebapp1
    spec:
      nodeSelector:
        env: production
      containers:
      - name: mywebapp-ptr
        image: chaitannyaa/calculator:latest
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
